[package]
name = "HamsterDrive"
version = "0.1.0"
edition = "2021"

[dependencies]
winsafe = { version = "0.0.17", features = ["kernel", "user"] }
eframe = "0.28.1"
egui = "0.28.1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }